<a href="https://colab.research.google.com/github/rechalgavit/DataScience_Training/blob/main/day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

In [14]:
arr = np.array([2,4,6,8,10,12])
print(arr)
print(type(arr))

[ 2  4  6  8 10 12]
<class 'numpy.ndarray'>


In [15]:
arr.shape

(6,)

In [16]:
arr.mean()

7.0

In [17]:
arr.max()

12

In [25]:
b = np.array([2,'4','6',8,10])

In [26]:
b

array(['2', '4', '6', '8', '10'], dtype='<U21')

In [31]:
c = np.arange(7,71,7)

In [32]:
c

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [35]:
d = np.arange(100)

In [36]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
c.max(axis=0)

70

In [42]:
two_d=np.array([[1,3,5],[9,7,5]])
print(two_d,'Dimension=',two_d.ndim,)

[[1 3 5]
 [9 7 5]] Dimension= 2


In [43]:
two_d[0:2,1:3]

array([[3, 5],
       [7, 5]])

In [64]:
d=d.reshape(10,10)

In [65]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [66]:
d.max()

99

In [67]:
d.max(axis=0)

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [68]:
d.max(axis=1)

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [69]:
d.sum(axis=0)

array([450, 460, 470, 480, 490, 500, 510, 520, 530, 540])

In [70]:
d.sum(axis=1)

array([ 45, 145, 245, 345, 445, 545, 645, 745, 845, 945])

In [72]:
fa = np.array([1,2,3])
sa = np.array([9,7,6])
print(np.concatenate((fa,sa)))

[1 2 3 9 7 6]
